name: Sync with upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # täglich um 04:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add upstream and merge
        run: |
          git remote add upstream https://github.com/Ruddernation-Designs/Adobe-URL-Block-List.git
          git fetch upstream
          git merge upstream/master --allow-unrelated-histories --no-edit || true

      - name: Push changes
        run: |
          git push origin master || true
